### ISSUE TITLE
no work

### ISSUE THREAD

**Issue by vladivdv** [jreenen/com.jreenen.homeyharmonyhub#53] opened 2019-02-20 22:48 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Homey firmware version: [e.g. 1.5.12]
 - App version [e.g. 1.2.1]

**Additional context**

**Comment by vladivdv** [comment] 2019-02-20 22:49
hi plagin no work

**Comment by vladivdv** [comment] 2019-02-20 22:49
pls help

**Comment by jreenen** [comment] 2019-02-21 10:15
Duplicate of #49 to keep it central I will close this issue, please use #49 to track progress and further comments.

**Closed by jreenen** 2019-02-21 10:15 UTC
