### ISSUE TITLE
Harmont app stopped working after homey 2.0.4 update

### ISSUE THREAD

**Issue by maaikekaasenbrood** [jreenen/com.jreenen.homeyharmonyhub#57] opened 2019-02-24 09:48 UTC
App stopped working after homey 2.0.4 update. Restarting app, restarting harmony hub and rebooting homey did not fix anything

**Comment by rpbras** [comment] 2019-02-24 10:45
I also updated to 2.04. And the app still works as it should for me.

**Comment by jreenen** [comment] 2019-02-24 11:39
Duplicate of #49 to keep it central I will close this issue, please use #49 to track progress and further comments.

**Closed by jreenen** 2019-02-24 11:39 UTC
