### ISSUE TITLE
Harmony offline

### ISSUE THREAD

**Issue by nieuwe** [jreenen/com.jreenen.homeyharmonyhub#56] opened 2019-02-23 19:28 UTC
Hello

Don’t know if it is allready reported but my devices show as offline 
The app is running and restarting it doesn’t resolve the offline states

**Comment by jreenen** [comment] 2019-02-24 08:39
Probably a duplicate of #49 to keep it central I will close this issue, please use #49 to track progress and further comments.

**Closed by jreenen** 2019-02-24 08:39 UTC
