### ISSUE TITLE
Can see Hub but then get error

### ISSUE THREAD

**Issue by casper181** [jreenen/com.jreenen.homeyharmonyhub#50] opened 2019-02-19 20:22 UTC
When trying to add devices or routines I get a network error despite being able to see the hub

**Comment by Wiltjer** [comment] 2019-02-19 21:01
I see the hub but no activitys

**Comment by jreenen** [comment] 2019-02-20 12:13
Duplicate of #49 to keep it central I will close this issue, please use #49 to track progress and further comments.

**Closed by jreenen** 2019-02-20 12:13 UTC
